"""shal#340 D2: the pure check functions of dev/e2e/story.py, run against a
real evidence.json (produced by the first version of the story on one OS and
committed at tests/data/e2e/sample-evidence.json — no hand-written fixture).

These tests never touch a venv, a subprocess, or the network: every check
function takes the same JSON/exit-code shape the real story already
produced, and this file just proves the function agrees with what is on
disk. A regression in the *logic* (not the *environment*) fails here, fast.
"""
from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path
from types import ModuleType

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SAMPLE_EVIDENCE = REPO_ROOT / "tests" / "data" / "e2e" / "sample-evidence.json"
WORKFLOW = REPO_ROOT / ".github" / "workflows" / "e2e-clean-machine.yml"


def _load_story() -> ModuleType:
    spec = importlib.util.spec_from_file_location("story", REPO_ROOT / "dev" / "e2e" / "story.py")
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    sys.modules["story"] = mod
    spec.loader.exec_module(mod)
    return mod


story = _load_story()


def _evidence() -> dict:
    return json.loads(SAMPLE_EVIDENCE.read_text(encoding="utf-8"))


def _by_id(evidence: dict, check_id: str) -> dict:
    return next(c for c in evidence["checks"] if c["id"] == check_id)


def test_sample_evidence_has_the_required_shape():
    evidence = _evidence()
    assert evidence["os"]
    assert evidence["python"]
    for pkg in ("pyshal", "shal-arena", "pytest-shal", "bricks-engine"):
        v = evidence["versions"][pkg]
        assert v["version"] and v["sha"] and v["repo"] and v["filename"] and v["sha256"]
    for check in evidence["checks"]:
        assert set(check) == {"id", "result", "log"}
        assert check["result"] in ("pass", "fail")


_RERUN = "rerun-command-irrelevant-for-a-passing-check"


def test_virtual_bench_pass_check_agrees_with_the_recorded_evidence():
    recorded = _by_id(_evidence(), "virtual_bench_pass")
    doc = json.loads(recorded["log"])
    assert story.check_virtual_bench_pass(doc, story.EXIT_PASS, _RERUN) == recorded


def test_virtual_bench_unplug_dmm_check_agrees_with_the_recorded_evidence():
    recorded = _by_id(_evidence(), "virtual_bench_unplug_dmm")
    doc = json.loads(recorded["log"])
    assert story.check_virtual_bench_unplug_dmm(doc, story.EXIT_UNREACHABLE, _RERUN) == recorded


def test_arena_score_file_checks_agree_with_the_recorded_evidence():
    # issue #403: a real sample (rule 8) -- `score_file_exists` alone used to
    # be the only thing this checked, which is why the OLD sample's cells
    # showed `turns: 0, faults_caught: 0` and still read "pass". This sample
    # (regenerated by actually running `run_arena_task_score_file` through a
    # real shal_arena) has real numbers: turns=2 on every level, and
    # faults_caught=1 on medium/hard, whose realized fault is not "ok".
    evidence = _evidence()
    for level in story.ARENA_TASK_LEVELS:
        recorded = _by_id(evidence, f"arena_{level}_score_file")
        logged = json.loads(recorded["log"])
        answer_doc = {"score": logged["score"], "correct": logged["correct"],
                      "disqualified": logged["disqualified"]}
        assert story.check_arena_score_file(
            level, logged["score_file_exists"], answer_doc, _RERUN) == recorded


def test_arena_score_file_check_catches_zero_turns():
    # the bug this ticket fixes: a score file can exist with `turns: 0`
    # (the run was never measured) and the old check still passed.
    score = {"task_id": "easy", "fault_type": "ok", "faults_caught": 0, "turns": 0}
    answer_doc = {"score": score, "correct": True, "disqualified": False}
    result = story.check_arena_score_file("easy", True, answer_doc, _RERUN)
    assert result["result"] == "fail"


def test_arena_score_file_check_catches_an_uncaught_fault():
    # a task whose realized fault was NOT "ok" (`fault_type`) but the run
    # scored `faults_caught: 0` -- the fault existed and was missed.
    score = {"task_id": "medium", "fault_type": "low_voltage", "faults_caught": 0, "turns": 2}
    answer_doc = {"score": score, "correct": False, "disqualified": False}
    result = story.check_arena_score_file("medium", True, answer_doc, _RERUN)
    assert result["result"] == "fail"


@pytest.mark.parametrize("correct,disqualified", [(False, False), (True, True)])
def test_arena_score_file_check_catches_wrong_or_disqualified(correct, disqualified):
    score = {"task_id": "hard", "fault_type": "high_voltage", "faults_caught": 1, "turns": 2}
    answer_doc = {"score": score, "correct": correct, "disqualified": disqualified}
    result = story.check_arena_score_file("hard", True, answer_doc, _RERUN)
    assert result["result"] == "fail"


def test_arena_score_file_check_passes_on_a_fault_free_task_with_zero_caught():
    # `fault_type == "ok"` (no real fault this run): `faults_caught: 0` is
    # correct, not a missed fault -- the check must not demand a nonzero
    # count where there was never a fault to catch.
    score = {"task_id": "easy", "fault_type": "ok", "faults_caught": 0, "turns": 2}
    answer_doc = {"score": score, "correct": True, "disqualified": False}
    result = story.check_arena_score_file("easy", True, answer_doc, _RERUN)
    assert result["result"] == "pass"


def test_arena_bench_destroyed_check_agrees_with_the_recorded_evidence():
    recorded = _by_id(_evidence(), "arena_bench_destroyed")
    logged = json.loads(recorded["log"])
    doc = {"with_shal": {"destroyed": logged["with_shal_destroyed"]},
          "without_shal": {"destroyed": logged["without_shal_destroyed"]}}
    assert story.check_arena_bench_destroyed(doc, _RERUN) == recorded


def test_arena_bench_destroyed_check_catches_a_regression():
    # if the SHAL side's gate ever broke, the story's own check must fail,
    # not quietly report the old "pass".
    doc = {"with_shal": {"destroyed": 3}, "without_shal": {"destroyed": 10}}
    assert story.check_arena_bench_destroyed(doc, _RERUN)["result"] == "fail"
    doc = {"with_shal": {"destroyed": 0}, "without_shal": {"destroyed": 0}}
    assert story.check_arena_bench_destroyed(doc, _RERUN)["result"] == "fail"


def test_virtual_bench_pass_check_catches_a_wrong_exit_code():
    doc = {"verdict": "pass", "cause": None}
    assert story.check_virtual_bench_pass(doc, 1, _RERUN)["result"] == "fail"


def test_virtual_bench_unplug_check_catches_a_verdict_that_is_not_an_error():
    doc = {"verdict": "pass", "cause": None}
    result = story.check_virtual_bench_unplug_dmm(doc, story.EXIT_UNREACHABLE, _RERUN)
    assert result["result"] == "fail"


def test_arena_demo_check_passes_when_both_files_exist():
    # issue #410 Done-when: "the same test runs in the clean-machine
    # story" -- no committed evidence yet (this check is new), so this is
    # synthetic input, same as the `_catches_a_...` tests above.
    doc = {"ok": True, "record_path": "/tmp/x.arena-record.json", "card_path": "/tmp/x.card.html"}
    result = story.check_arena_demo(doc, story.EXIT_PASS, True, True, _RERUN)
    assert result["result"] == "pass"


def test_arena_demo_check_catches_a_missing_file():
    doc = {"ok": True, "record_path": "/tmp/x.arena-record.json", "card_path": "/tmp/x.card.html"}
    result = story.check_arena_demo(doc, story.EXIT_PASS, True, False, _RERUN)
    assert result["result"] == "fail"


def test_arena_demo_check_catches_a_failed_run():
    doc = {"ok": False, "record_path": "/tmp/x.arena-record.json", "card_path": "/tmp/x.card.html"}
    result = story.check_arena_demo(doc, story.EXIT_PASS, True, True, _RERUN)
    assert result["result"] == "fail"


def test_wheel_installed_check_agrees_with_the_recorded_evidence():
    recorded = _by_id(_evidence(), "wheel_installed_bricks-engine")
    assert recorded["result"] == "pass"
    assert story.check_wheel_installed(
        "bricks-engine", "0.5.0", True, "0.5.0\n", _RERUN) == recorded


def test_a_failed_checks_log_starts_with_the_rerun_command():
    # CTO review on #340 (D2 spec): an agent reading evidence.json must find
    # the exact command to rerun right at the start of a failed check's log.
    doc = {"verdict": "fail"}
    result = story.check_virtual_bench_pass(doc, 1, "the exact rerun command")
    assert result["result"] == "fail"
    assert result["log"].startswith("rerun: the exact rerun command\n")


def test_story_gets_the_bench_from_the_packaged_sample_not_a_repo_checkout_path():
    # #384: the virtual bench moved into pyshal's own `virtual-bench` sample, so the
    # clean-machine story must reach it the same way a buyer would — through the
    # venv's own `shal docs --sample virtual-bench --to <dir>` — never by assuming a
    # repo checkout path exists on the clean machine.
    text = (REPO_ROOT / "dev" / "e2e" / "story.py").read_text(encoding="utf-8")
    assert "examples/demos/virtual-bench" not in text
    assert '"demos"' not in text and '"virtual-bench"' in text   # no Path()-built demo path
    assert "docs --sample virtual-bench" in text or '"--sample", "virtual-bench"' in text


def test_pull_request_trigger_covers_the_sample_and_cli_py():
    # #385: the PR path filter must cover the virtual-bench sample's packaged
    # copy and src/shal/cli.py (the `shal docs --sample` entry point #384's
    # story now depends on), not just the original examples/demos/ path.
    config = yaml.safe_load(WORKFLOW.read_text("utf-8"))
    on = config[True] if True in config else config["on"]
    paths = on["pull_request"]["paths"]
    assert "src/shal/samples/virtual-bench/**" in paths
    assert "src/shal/cli.py" in paths
